### ISSUE TITLE
When I shoot someone it crashes the game near instantly

### ISSUE THREAD

**Issue by waffla15** [Kevin0M16/kevs-gore#2]
please fix it as the mod looks awesome

**Comment by Kevin0M16** [comment]
This has been running in my server since 2021 without issues. If it is crashing there is a conflict with another resource, more than likely using gta5.meta. If you want to see it: https://servers.fivem.net/servers/detail/zo7ok9

**Comment by waffla15** [comment]
![image](https://github.com/user-attachments/assets/21adb4d0-0dfb-456b-8c01-bd34e28704c3)

This was instant after I started the resource, this is a fresh server and I checked my few resources and nothing else uses the gta5.meta file

**Comment by waffla15** [comment]
![image](https://github.com/user-attachments/assets/d4e6e814-bb02-4e8e-a136-fd05e0f7d273)

**Comment by Kevin0M16** [comment]
Thanks for the screenshot. The issue is that you renamed the resource and the path fails. Leave it as kevs-gore and you should be good.

**Comment by waffla15** [comment]
Nah I've tried it with the resource named kevs-gore as well and still same error, idk why but it doesn't work dude, I tried it on Ur server and I like the gore but it doesn't work for me, please update it or put me on the path of how I can get this to work without GTA5.meta if that is the file causing the issue
